// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: backpack.proto

public final class BackpackOuterClass {
  private BackpackOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BackpackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Backpack)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string string1 = 1;</code>
     */
    java.lang.String getString1();
    /**
     * <code>string string1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getString1Bytes();

    /**
     * <code>int32 integer1 = 2;</code>
     */
    int getInteger1();

    /**
     * <code>int32 integer2 = 3;</code>
     */
    int getInteger2();
  }
  /**
   * Protobuf type {@code Backpack}
   */
  public  static final class Backpack extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Backpack)
      BackpackOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Backpack.newBuilder() to construct.
    private Backpack(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Backpack() {
      string1_ = "";
      integer1_ = 0;
      integer2_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Backpack(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              string1_ = s;
              break;
            }
            case 16: {

              integer1_ = input.readInt32();
              break;
            }
            case 24: {

              integer2_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BackpackOuterClass.internal_static_Backpack_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BackpackOuterClass.internal_static_Backpack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BackpackOuterClass.Backpack.class, BackpackOuterClass.Backpack.Builder.class);
    }

    public static final int STRING1_FIELD_NUMBER = 1;
    private volatile java.lang.Object string1_;
    /**
     * <code>string string1 = 1;</code>
     */
    public java.lang.String getString1() {
      java.lang.Object ref = string1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        string1_ = s;
        return s;
      }
    }
    /**
     * <code>string string1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getString1Bytes() {
      java.lang.Object ref = string1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        string1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTEGER1_FIELD_NUMBER = 2;
    private int integer1_;
    /**
     * <code>int32 integer1 = 2;</code>
     */
    public int getInteger1() {
      return integer1_;
    }

    public static final int INTEGER2_FIELD_NUMBER = 3;
    private int integer2_;
    /**
     * <code>int32 integer2 = 3;</code>
     */
    public int getInteger2() {
      return integer2_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getString1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, string1_);
      }
      if (integer1_ != 0) {
        output.writeInt32(2, integer1_);
      }
      if (integer2_ != 0) {
        output.writeInt32(3, integer2_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getString1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, string1_);
      }
      if (integer1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, integer1_);
      }
      if (integer2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, integer2_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BackpackOuterClass.Backpack)) {
        return super.equals(obj);
      }
      BackpackOuterClass.Backpack other = (BackpackOuterClass.Backpack) obj;

      boolean result = true;
      result = result && getString1()
          .equals(other.getString1());
      result = result && (getInteger1()
          == other.getInteger1());
      result = result && (getInteger2()
          == other.getInteger2());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STRING1_FIELD_NUMBER;
      hash = (53 * hash) + getString1().hashCode();
      hash = (37 * hash) + INTEGER1_FIELD_NUMBER;
      hash = (53 * hash) + getInteger1();
      hash = (37 * hash) + INTEGER2_FIELD_NUMBER;
      hash = (53 * hash) + getInteger2();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BackpackOuterClass.Backpack parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BackpackOuterClass.Backpack parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BackpackOuterClass.Backpack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BackpackOuterClass.Backpack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BackpackOuterClass.Backpack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BackpackOuterClass.Backpack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BackpackOuterClass.Backpack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BackpackOuterClass.Backpack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BackpackOuterClass.Backpack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BackpackOuterClass.Backpack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BackpackOuterClass.Backpack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BackpackOuterClass.Backpack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BackpackOuterClass.Backpack prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Backpack}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Backpack)
        BackpackOuterClass.BackpackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BackpackOuterClass.internal_static_Backpack_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BackpackOuterClass.internal_static_Backpack_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BackpackOuterClass.Backpack.class, BackpackOuterClass.Backpack.Builder.class);
      }

      // Construct using BackpackOuterClass.Backpack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        string1_ = "";

        integer1_ = 0;

        integer2_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BackpackOuterClass.internal_static_Backpack_descriptor;
      }

      public BackpackOuterClass.Backpack getDefaultInstanceForType() {
        return BackpackOuterClass.Backpack.getDefaultInstance();
      }

      public BackpackOuterClass.Backpack build() {
        BackpackOuterClass.Backpack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public BackpackOuterClass.Backpack buildPartial() {
        BackpackOuterClass.Backpack result = new BackpackOuterClass.Backpack(this);
        result.string1_ = string1_;
        result.integer1_ = integer1_;
        result.integer2_ = integer2_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BackpackOuterClass.Backpack) {
          return mergeFrom((BackpackOuterClass.Backpack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BackpackOuterClass.Backpack other) {
        if (other == BackpackOuterClass.Backpack.getDefaultInstance()) return this;
        if (!other.getString1().isEmpty()) {
          string1_ = other.string1_;
          onChanged();
        }
        if (other.getInteger1() != 0) {
          setInteger1(other.getInteger1());
        }
        if (other.getInteger2() != 0) {
          setInteger2(other.getInteger2());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BackpackOuterClass.Backpack parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BackpackOuterClass.Backpack) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object string1_ = "";
      /**
       * <code>string string1 = 1;</code>
       */
      public java.lang.String getString1() {
        java.lang.Object ref = string1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          string1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string string1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getString1Bytes() {
        java.lang.Object ref = string1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          string1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string string1 = 1;</code>
       */
      public Builder setString1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        string1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string string1 = 1;</code>
       */
      public Builder clearString1() {
        
        string1_ = getDefaultInstance().getString1();
        onChanged();
        return this;
      }
      /**
       * <code>string string1 = 1;</code>
       */
      public Builder setString1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        string1_ = value;
        onChanged();
        return this;
      }

      private int integer1_ ;
      /**
       * <code>int32 integer1 = 2;</code>
       */
      public int getInteger1() {
        return integer1_;
      }
      /**
       * <code>int32 integer1 = 2;</code>
       */
      public Builder setInteger1(int value) {
        
        integer1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 integer1 = 2;</code>
       */
      public Builder clearInteger1() {
        
        integer1_ = 0;
        onChanged();
        return this;
      }

      private int integer2_ ;
      /**
       * <code>int32 integer2 = 3;</code>
       */
      public int getInteger2() {
        return integer2_;
      }
      /**
       * <code>int32 integer2 = 3;</code>
       */
      public Builder setInteger2(int value) {
        
        integer2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 integer2 = 3;</code>
       */
      public Builder clearInteger2() {
        
        integer2_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Backpack)
    }

    // @@protoc_insertion_point(class_scope:Backpack)
    private static final BackpackOuterClass.Backpack DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BackpackOuterClass.Backpack();
    }

    public static BackpackOuterClass.Backpack getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Backpack>
        PARSER = new com.google.protobuf.AbstractParser<Backpack>() {
      public Backpack parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Backpack(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Backpack> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Backpack> getParserForType() {
      return PARSER;
    }

    public BackpackOuterClass.Backpack getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Backpack_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Backpack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016backpack.proto\"?\n\010Backpack\022\017\n\007string1\030" +
      "\001 \001(\t\022\020\n\010integer1\030\002 \001(\005\022\020\n\010integer2\030\003 \001(" +
      "\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Backpack_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Backpack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Backpack_descriptor,
        new java.lang.String[] { "String1", "Integer1", "Integer2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
